#!/usr/bin/env bash

# -*- coding: utf-8 -*-

# Copyright (C) 2019 UPR.

# iroko is free software; you can redistribute it and/or modify it under the
# terms of the MIT License; see LICENSE file for more details.

while IFS="" read -r p || [ -n "$p" ]
do
  printf '%s\n' "$p"
  nohup iroko harvester fetch-url $p ../data/harvest &>/dev/null &

done < ./urls
